# Configuration for RAG pipeline and model selection
# ------------------------------------------------------------------
# Provider selection: "openai", "gemini" or "deepseek"
provider: "deepseek"

# OpenAI settings (used if provider == "openai")
openai:
  api_key: ""
  model: "gpt-4.1"

# Google Gemini settings (used if provider == "gemini")
gemini:
  api_key: ""
  model: "gemini-2.0-flash"

# DeepSeek settings (used if provider == "deepseek")
deepseek:
  api_key: ""
  base_url: "https://api.deepseek.com"
  model: "deepseek-reasoner"